### PR TITLE
Zeitwerk fixes

### PR DESCRIPTION
**Pull request by agnieszkajacek**

### CODE REVIEW

**Comment by andrewmarkle** [comment]
The file moves / renames here make perfect sense for Zeitwerk. Looks good! 

Only question: why add sprockets?

**Comment by agnieszkajacek** [comment]
@andrewmarkle That was 2 months ago... I had problems with manifest.js -> https://app.travis-ci.com/github/spree-contrib/spree_avatax_official/jobs/512327938 and probably that's why I added sprockets

**Comment by GrzegorzStochel** [comment]
here is more info about the solution with sprockets: https://stackoverflow.com/questions/58339607/why-does-rails-fails-to-boot-with-expected-to-find-a-manifest-file-in-app-asse

**Review by andrewmarkle — APPROVED** [review]
Cool. Thanks for the added context. This LGTM.

**Comment by andrewmarkle** [comment]
Hrmm. Looks like I don't have write access (probably a good thing! 😂). @glongman Do you mind taking a look?

**Comment by glongman** [comment]
@andrewmarkle should a fed look at this manifest requirement?

**Review by andrewmarkle — APPROVED** [review]

**Review by andrewmarkle — APPROVED** [review]

**Review by GrzegorzStochel — APPROVED** [review]

**Comment by aneskap** [comment]
@damianlegawiec would you have time to merge this PR? :)

**Comment by agnieszkajacek** [comment]
But @damianlegawiec but please, do not delete this branch, because our gemfile points to that branch though so don’t delete it until we can point our gemfile back to the right spot
Thanks! :)

**Review by damianlegawiec — APPROVED** [review]

**Pull request merged**
